# Generated by Django 5.2.6 on 2025-09-17 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_ministry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_list_type', models.CharField(choices=[('1p1w1f', '1 Praise, 1 Worship, 1 Fellowship'), ('2p1w1f', '2 Praise, 1 Worship, 1 Fellowship'), ('2p2w1f', '2 Praise, 2 Worship, 1 Fellowship'), ('custom', 'Custom')], max_length=10)),
                ('status', models.CharField(choices=[('for_approval', 'For Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='for_approval', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lineups', to='music_ministry.member')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='music_ministry.event')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_type', models.CharField(choices=[('praise', 'Praise'), ('high_praise', 'High Praise'), ('worship', 'Worship'), ('high_worship', 'High Worship'), ('fellowship', 'Fellowship')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_ministry.lineup')),
            ],
            options={
                'ordering': ['order', 'song_type'],
                'unique_together': {('lineup', 'order')},
            },
        ),
    ]
