# Generated by Django 5.2.6 on 2025-09-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_ministry', '0002_lineup_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='song_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
