# Generated by Django 5.2.6 on 2025-09-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_ministry', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventassignment',
            name='assigned_role',
            field=models.CharField(choices=[('worship_leader', 'Worship Leader'), ('guitarist', 'Guitarist'), ('keys', 'Keys'), ('drummer', 'Drummer'), ('bassist', 'Bassist'), ('vocalist', 'Vocalist'), ('technical', 'Technical'), ('dancer', 'Dancer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='musician_role',
            field=models.CharField(choices=[('worship_leader', 'Worship Leader'), ('guitarist', 'Guitarist'), ('keys', 'Keys'), ('drummer', 'Drummer'), ('bassist', 'Bassist'), ('vocalist', 'Vocalist'), ('technical', 'Technical'), ('dancer', 'Dancer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('technical', 'Technical'), ('dancer', 'Dancer')], default='member', max_length=10),
        ),
    ]
