# Generated by Django 5.2.6 on 2025-09-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_ministry', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes for assigned members'),
        ),
    ]
