# Generated by Django 5.2.6 on 2025-10-03 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_ministry', '0007_event_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('testament', models.CharField(choices=[('old', 'Old Testament'), ('new', 'New Testament')], max_length=3)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['testament', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField()),
                ('verse_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='music_ministry.biblebook')),
            ],
            options={
                'ordering': ['book__order', 'chapter', 'verse_number'],
                'unique_together': {('book', 'chapter', 'verse_number')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('is_bible_related', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_ministry.bibleverse')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
